### PR TITLE
Add messages to the fallback attribute

### PR DESCRIPTION
**Pull request by eisuke**
Add messages to the fallback attribute for IRC clients connecting to Slack.

### CODE REVIEW

**Comment by sonots** [comment]
Could you add an option for this? I am comfortable with current behavior.

**Comment by eisuke** [comment]
> Could you add an option for this?

You’ve got a point. fb353db

**Comment by sonots** [comment]
thx!

**Comment by sonots** [comment]
@eisuke By the way, if you do not specify `title` option, https://github.com/sowawa/fluent-plugin-slack/blob/master/lib/fluent/plugin/out_slack.rb#L301-L314 this lines are used, so all messages should be popped up. Was this not enough for you?

**Comment by eisuke** [comment]
No, without `title` option is not enough.

My problem is that some people use official slack client, and others connect to Slack via IRC client.
The former want to watch richly-formatted messages with `title` attribute, the later want to get information equal to the former (the later can only get title).

**Comment by sonots** [comment]
Okay, thanks

**Comment by sonots** [comment]
0.6.3 is released!

**Comment by eisuke** [comment]
thanks!

**Pull request merged**
