### PR TITLE
Migrate to v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
Hi, I've tried to migrate using v0.14 API.
Could you review this change?

* Keep Buffered output plugin
* Depends on new tag/time manipulation style instead of old mixin based style

### CODE REVIEW

**Comment by sonots** [comment]
Thanks! What I am currently thinking is how to maintain this plugin for both v0.12 and v0.14.
I know some gems which supports various versions of rails in one branch. I may take such approach for my plugins so that we do not need to maintain two separated branches and two separated gems.

I will think of it later, but thanks anyway.

**Comment by cosmo0920** [comment]
I'll postponed this PR until v2.

**Comment by cscollett** [comment]
Is this still planned now v1 is out?

**Comment by cosmo0920** [comment]
No. We postponed for now.
I'm closing this.

**Pull request closed without merging**
