### PR TITLE
Add auto_channels_create option

### PR DESCRIPTION
**Pull request by sonots**
I added `auto_channels_create` option which enables to create a channel automatically if it does not exist. 

This option is available only for Web API with a token of a Normal User (Bot User can not create a channel). See https://api.slack.com/bot-users for Normal User and Bot User.

### CODE REVIEW

**Comment by sonots** [comment]
I gonna merge.

**Comment by sonots** [comment]
@sowawa can you give me a right to release gem? You can add me by executing a command:

```
gem owner fluent-plugin-slack -a sonots@gmail.com
```

**Comment by sowawa** [comment]
I added your account.
Thanks :smile:

**Comment by sonots** [comment]
Thanks :)

**Comment by sonots** [comment]
v0.5.1 is released!

**Comment by sowawa** [comment]
:+1:

**Pull request merged**
